// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTodayDuration() {
  return window['go']['main']['App']['GetTodayDuration']();
}

export function GetTodayTask() {
  return window['go']['main']['App']['GetTodayTask']();
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function SaveTask(arg1) {
  return window['go']['main']['App']['SaveTask'](arg1);
}
