// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function GetTodayTask():Promise<Array<database.TaskModel>>;

export function Log(arg1:string):Promise<void>;

export function SaveTask(arg1:database.TaskModel):Promise<void>;
